<?php
$_SESSION['test'] = 'st';
echo "<h1>".$_SERVER["REMOTE_ADDR"]."</h1>";
//importing bootstrap 5.1.3 via cdn
echo $this->tag->stylesheetLink('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', true);
echo $this->tag->stylesheetLink('css/main.css');
echo " | ";

echo $this->tag->linkTo('signup', 'Sign Up Here!');
echo " | ";
echo $this->tag->linkTo('login', 'Login!');
echo " | ";
echo $this->tag->linkTo('/index/insta', 'INSTAGRAM (Real)');
echo " | ";
echo $this->tag->linkTo('admin/index/1', 'All Users');
echo " | ";
if (isset($_SESSION['user'])) {
    echo '<a class="float-end btn btn-secondary" href = "/login/logout">Log Out  ' . $_SESSION['user']['name'] . '</a>';
}
echo $this->tag->linkTo('index/test/3', "Index->test(3)");
echo "<span class='z-muted z-auto-pad'>This will just will just print 3 on the next page </span>";

echo $this->tag->tagHtml(
    'p',
    ["class" => 'fs-1 fw-bold text-light']
);
echo htmlspecialchars("This is inside a <p> tag");
echo $this->tag->tagHtmlClose('p');
echo "<div class='container bg-warning rounded-3 p-3'>";
echo $this->tag->form(array("", "method" => "POST", "class" => 'container-fluid form-group overflow-hidden'));
echo $this->tag->textField(array(
    "name" => "Alien",
    "placeholder" => "Alien",
    "class" => 'from-control mt-2',
));
echo "<br>";
echo "<p class=' fs-2 text-dark  mb-0 mt-3'>";
echo "Enter Javascript code to execute: ";
echo "</p>";
echo "<p class='text-dark' >use print(string) to print to current page</p>";
echo $this->tag->submitButton(array('class' => 'btn btn-primary mt-2 d-block'));


echo $this->tag->textArea(array(
    "name" => "Coprus",
    "class" => 'from-control mt-2 rounded p-2 bg-dark text-info border-none',
    "rows" => 15,
    "cols" => 75,
    "value" => $post
));
echo "<p class='text-dark align-top d-inline-block p-3'>Output:</p>";
echo "<pre id='output' class='text-dark align-top d-inline-block pt-3'></pre>";
echo "</form>";
echo "</div>";
echo $put;

echo $this->tag->javascriptInclude(
    "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js",
    true
);
echo $this->tag->javascriptInclude("https://code.jquery.com/jquery-3.6.0.js", true);
echo $this->tag->javascriptInclude("js/main.js");
