<?php
use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;
use Phalcon\Forms\Element\Select;

echo "<h1>Hello World</h1>";
//importing bootstrap 5.1.3 via cdn
echo $this->tag->stylesheetLink('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', true);
echo $this->tag->stylesheetLink('css/main.css');


echo $this->tag->linkTo('signup', 'Sign Up Here!');
echo '<br>';
echo $this->tag->linkTo('index/test/3', "Index->test(3)");
echo "<span class='z-muted z-auto-pad'>This will just will just print 3 on the next page </span>";
echo '<br>';
echo $this->tag->tagHtml(
    'p',
    ["class"=>'fs-1 fw-bold text-light']
);
echo htmlspecialchars("This is inside a <p> tag");
echo $this->tag->tagHtmlClose('p');
echo "<div class='container bg-warning rounded-3 p-3'>";
echo $this->tag->form(array("index/dost", "method" => "POST", "class" => 'container-fluid form-group overflow-hidden'));
echo $this->tag->textField(array("name" => "bihar", "class" => 'from-control mt-2'));
echo "<br>";
echo "<p class='text-muted'>Testing post request on Index->dost()</p>";
echo "<br>";
echo $this->tag->submitButton(array('class' => 'btn btn-primary mt-2 d-block ms-auto'));
echo "</div>";
