<?php require '/var/www/html/app/views/common/style.php' ?>
<div class='row mt-2 container'>
    <div class='col'>
    <img src="https://www.instagram.com/static/images/homepage/phones/home-phones.png/1dc085cdb87d.png">
    </div>
    <div class='89 col-4 p-5 bg-light border text-dark rounded-1'>
        <h2 class='mt-5 mb-3' > Real Instagram </h2>
        <h3 class='mt-0 mb-1' >Login</h3>
        <form action="" method='post' class='text-center form-group'>
            <input name='email' placeholder="Email" type='email' class='form-control mb-2'>
            <input name='pass' placeholder="Password" type='password' class='form-control mb-2'>
            <input name='login' value="Login" type='submit' class='form-control mb-2 btn-info'>
        </form>
    </div>
</div>