<h2>Sign up using this form</h2>

<div class=''>
    <form class='w-25 m-auto' action="/signup/register" method="POST">
    <input type='text' name='name' placeholder="Name" class='form-control mt-2'>
    <input type='email' name='email' placeholder="Email" class='form-control mt-2'>
    <input type='text' name='pass' placeholder="Password" class='form-control mt-2'>
    <input type='submit' class='form-control btn-success mt-2'>
    </form>
</div>